### ISSUE TITLE
TypeScript is throwing an error of incompatible types

### ISSUE THREAD

**Issue by heavenly-zy** [zhiyuanzmj/transformer-attributify-jsx-sg#4]
In my react-ts project created with Vite, I encountered the following type error when importing `transformer-attributify-jsx-sg` in `uno.config.ts`.
![image](https://github.com/zhiyuanzmj/transformer-attributify-jsx-sg/assets/50657815/94734889-17a8-4f32-baa3-95a9b7a380e8)

```raw
Type 'import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").SourceCodeTransformer' is not assignable to type 'import("stackblitz:/node_modules/@unocss/core/dist/index").SourceCodeTransformer'.
  Types of property 'transform' are incompatible.
    Type '(code: import("stackblitz:/node_modules/magic-string/dist/magic-string.es").default, id: string, ctx: import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").UnocssPluginContext<import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/di...' is not assignable to type '(code: import("stackblitz:/node_modules/magic-string/dist/magic-string.es").default, id: string, ctx: import("stackblitz:/node_modules/@unocss/core/dist/index").UnocssPluginContext<import("stackblitz:/node_modules/@unocss/core/dist/index").UserConfig<object>>) => import("stackblitz:/node_modules/@unocss/core/dist/in...'.
      Types of parameters 'ctx' and 'ctx' are incompatible.
        Type 'import("stackblitz:/node_modules/@unocss/core/dist/index").UnocssPluginContext<import("stackblitz:/node_modules/@unocss/core/dist/index").UserConfig<object>>' is not assignable to type 'import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").UnocssPluginContext<import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").UserConfig<object>>'.
          Types of property 'ready' are incompatible.
            Type 'Promise<import("stackblitz:/node_modules/unconfig/dist/shared/unconfig.e8f60d5d").a<import("stackblitz:/node_modules/@unocss/core/dist/index").UserConfig<object>>>' is not assignable to type 'Promise<import("stackblitz:/node_modules/unconfig/dist/shared/unconfig.e8f60d5d").a<import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").UserConfig<object>>>'.
              Type 'import("stackblitz:/node_modules/unconfig/dist/shared/unconfig.e8f60d5d").a<import("stackblitz:/node_modules/@unocss/core/dist/index").UserConfig<object>>' is not assignable to type 'import("stackblitz:/node_modules/unconfig/dist/shared/unconfig.e8f60d5d").a<import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").UserConfig<object>>'.
                Type 'import("stackblitz:/node_modules/@unocss/core/dist/index").UserConfig<object>' is not assignable to type 'import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").UserConfig<object>'.
                  Types of property 'rules' are incompatible.
                    Type 'import("stackblitz:/node_modules/@unocss/core/dist/index").Rule<object>[] | undefined' is not assignable to type 'import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").Rule<object>[] | undefined'.
                      Type 'import("stackblitz:/node_modules/@unocss/core/dist/index").Rule<object>[]' is not assignable to type 'import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").Rule<object>[]'.
                        Type 'import("stackblitz:/node_modules/@unocss/core/dist/index").Rule<object>' is not assignable to type 'import("stackblitz:/node_modules/transformer-attributify-jsx-sg/node_modules/@unocss/core/dist/index").Rule<object>'.
                          Type '[RegExp, DynamicMatcher<object>]' is not assignable to type 'Rule<object>'.
                            Type '[RegExp, DynamicMatcher<object>]' is not assignable to type '[string, CSSObject | CSSEntries]'.
                              Type at position 0 in source is not compatible with type at position 0 in target.
                                Type 'RegExp' is not assignable to type 'string'.(2322)
(alias) transformerAttributifyJsx(options?: TransformerAttributifyJsxOptions | undefined): SourceCodeTransformer
import transformerAttributifyJsx
```

Here is a reproduction: https://stackblitz.com/edit/vitejs-vite-cg41qh?file=uno.config.ts

**Comment by zhiyuanzmj** [comment]
No problem in my local project, stackblitz may not be supported.

**Comment by heavenly-zy** [comment]
> No problem in my local project, stackblitz may not be supported.在我的本地项目中没有问题，可能不支持 stackblitz。

The same issue also exists in my local project.
You can try running this [repo](https://github.com/heavenly-zy/react-mangosteen) locally to reproduce the issue.

**Comment by zhiyuanzmj** [comment]
It's worked fine on my m1 mac, Maybe you can try reinstalling it 
```sh
rm -rf node_modules && pnpm i
```
<img width="916" alt="image" src="https://github.com/zhiyuanzmj/transformer-attributify-jsx-sg/assets/32807958/e147ac51-aa21-447e-8ed4-e22b646f0311">

**Comment by heavenly-zy** [comment]
> It's worked fine on my m1 mac, Maybe you can try reinstalling it它在我的 m1 mac 上运行良好，也许您可以尝试重新安装它
> 
> ```shell
> rm -rf node_modules && pnpm i
> ```
> 
> <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/32807958/295761767-e147ac51-aa21-447e-8ed4-e22b646f0311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MzgxNzAsIm5iZiI6MTcwNDkzNzg3MCwicGF0aCI6Ii8zMjgwNzk1OC8yOTU3NjE3NjctZTE0N2FjNTEtYWEyMS00NDdlLThlZDQtZTIyYjY0NmYwMzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAxNTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTdiMTZmMzUzNjY4MWU4OWY2ZTllZjZlMTQ1ZmE0ZTk1MmU0ZGFkOTFiYzQxYjc3ZWVhNzBjMTI3N2IwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yS1wZ9_nmQn_uk5aWMSur36Q9hhcU4CHmI381ITfwzk">

You need to check `transformerAttributifyJsx()` in `transformers`,
```ts
  transformers: [
    // eslint-disable-next-line ts/ban-ts-comment
    // @ts-expect-error
    transformerAttributifyJsx(),
  ],
```
Please remove the two lines of comments on `transformerAttributifyJsx()` to see the error message.

**Comment by zhiyuanzmj** [comment]
Oh, Thank you, I've upgraded unocss version. 
please use v0.0.7 version

**Comment by heavenly-zy** [comment]
> Oh, Thank you, I've upgraded unocss version. please use v0.0.7 version

I have updated to version 0.0.7, but the problem still persists.
![image](https://github.com/zhiyuanzmj/transformer-attributify-jsx-sg/assets/50657815/68d288bc-619d-4237-b301-833e0db80c12)

**Comment by zhiyuanzmj** [comment]
try reInstall deps.
<img width="836" alt="image" src="https://github.com/zhiyuanzmj/transformer-attributify-jsx-sg/assets/32807958/68025285-a3d6-49d9-8be9-bd1e259dc671">

**Comment by zhiyuanzmj** [comment]
Or, update unocss to 0.58.3

**Comment by heavenly-zy** [comment]
> Or, update unocss to 0.58.3

Thank you, it is helpful to me. It is now working properly.
